-- MySQL Script generated by MySQL Workbench
-- Fri Apr 14 13:50:50 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ctsSaga
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ctsSaga
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ctsSaga` DEFAULT CHARACTER SET utf8 ;
USE `ctsSaga` ;

-- -----------------------------------------------------
-- Table `ctsSaga`.`EquipoComputo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ctsSaga`.`EquipoComputo` (
  `id_EquipoComputo` INT NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_EquipoComputo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctsSaga`.`Mantenimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ctsSaga`.`Mantenimiento` (
  `idMantenimiento` INT NOT NULL,
  `fecha_inicio` DATETIME NULL DEFAULT NULL,
  `fecha_final` DATETIME NULL,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  `id_EquipoComputo` INT NOT NULL,
  PRIMARY KEY (`idMantenimiento`),
  INDEX `fk_Mantenimiento_EquipoComputo1_idx` (`id_EquipoComputo` ASC) VISIBLE,
  CONSTRAINT `fk_Mantenimiento_EquipoComputo1`
    FOREIGN KEY (`id_EquipoComputo`)
    REFERENCES `ctsSaga`.`EquipoComputo` (`id_EquipoComputo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctsSaga`.`tipoActivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ctsSaga`.`tipoActivo` (
  `idActivo` INT NOT NULL,
  `varios` VARCHAR(45) NULL DEFAULT NULL,
  `mobiliario` VARCHAR(45) NULL DEFAULT NULL,
  `vehiculo` VARCHAR(45) NULL DEFAULT NULL,
  `disco duro` VARCHAR(45) NULL DEFAULT NULL,
  `id_EquipoComputo` INT NOT NULL,
  `marca` VARCHAR(45) NULL DEFAULT NULL,
  `modelo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idActivo`),
  INDEX `fk_tipoActivo_EquipoComputo1_idx` (`id_EquipoComputo` ASC) VISIBLE,
  CONSTRAINT `fk_tipoActivo_EquipoComputo1`
    FOREIGN KEY (`id_EquipoComputo`)
    REFERENCES `ctsSaga`.`EquipoComputo` (`id_EquipoComputo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctsSaga`.`Sede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ctsSaga`.`Sede` (
  `id_Sede` INT NOT NULL,
  `nombre_sede` VARCHAR(45) NULL DEFAULT NULL,
  `ubicacion` VARCHAR(45) NULL DEFAULT NULL,
  `proyecto` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Sede`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctsSaga`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ctsSaga`.`Factura` (
  `id_Factura` INT NOT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `imagen` VARCHAR(255) NULL DEFAULT NULL,
  `monto` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id_Factura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctsSaga`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ctsSaga`.`Area` (
  `id_Area` INT NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_Area`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctsSaga`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ctsSaga`.`Cargo` (
  `idCargos` INT NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `id_Area` INT NOT NULL,
  PRIMARY KEY (`idCargos`),
  INDEX `fk_Cargo_Area1_idx` (`id_Area` ASC) VISIBLE,
  CONSTRAINT `fk_Cargo_Area1`
    FOREIGN KEY (`id_Area`)
    REFERENCES `ctsSaga`.`Area` (`id_Area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctsSaga`.`Empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ctsSaga`.`Empleados` (
  `id_Empleados` INT NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `cumpleaños` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `num_empleado` VARCHAR(45) NULL DEFAULT NULL,
  `estatus` VARCHAR(45) NULL DEFAULT NULL,
  `id_cargo` INT NOT NULL,
  PRIMARY KEY (`id_Empleados`),
  INDEX `fk_Empleados_Cargos1_idx` (`id_cargo` ASC) VISIBLE,
  CONSTRAINT `fk_Empleados_Cargos1`
    FOREIGN KEY (`id_cargo`)
    REFERENCES `ctsSaga`.`Cargo` (`idCargos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctsSaga`.`Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ctsSaga`.`Inventario` (
  `idInventario` INT NOT NULL,
  `no_serie` VARCHAR(45) NULL DEFAULT NULL,
  `caracteristicas` VARCHAR(45) NULL DEFAULT NULL,
  `estado` INT NULL DEFAULT NULL,
  `tipoActivo_idActivo` INT NOT NULL,
  `id_Sede` INT NOT NULL,
  `id_factura` INT NULL,
  `id_empleado` INT NOT NULL,
  PRIMARY KEY (`idInventario`),
  INDEX `fk_Inventario_tipoActivo_idx` (`tipoActivo_idActivo` ASC) VISIBLE,
  INDEX `fk_Inventario_Sede1_idx` (`id_Sede` ASC) VISIBLE,
  INDEX `fk_Inventario_Factura1_idx` (`id_factura` ASC) VISIBLE,
  INDEX `fk_Inventario_Empleados1_idx` (`id_empleado` ASC) VISIBLE,
  CONSTRAINT `fk_Inventario_tipoActivo`
    FOREIGN KEY (`tipoActivo_idActivo`)
    REFERENCES `ctsSaga`.`tipoActivo` (`idActivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventario_Sede1`
    FOREIGN KEY (`id_Sede`)
    REFERENCES `ctsSaga`.`Sede` (`id_Sede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventario_Factura1`
    FOREIGN KEY (`id_factura`)
    REFERENCES `ctsSaga`.`Factura` (`id_Factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventario_Empleados1`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `ctsSaga`.`Empleados` (`id_Empleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
