
@api= http://localhost:4000/inventario

###Consulta todos
GET {{api}}
###Agregar a la tabla
POST {{api}}
content-type: application/json

{
    "Id_inventario":"CTS/MO/002/21Prueba2",
    "Serie": "V3Y1330",
    "Tipo": 4,
    "Marca": "ASUS",
    "Modelo": "003" 
}
###Consulta por id
Get {{api}}/2
###Eliminar por id
DELETE {{api}}/1
###Update inventario
PUT {{api}}/2
Content-Type: application/json

{
    "Id_inventario":"CTS/MO/002/21Prueba2",
    "Serie": "Prueba2",
    "Tipo": 4,
    "Marca": "Prueba2",
    "Modelo": "Prueba2"
}